# Generated by Django 4.2 on 2025-10-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_smtpaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMTPAccount',
        ),
    ]
