# Generated by Django 4.2 on 2025-10-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0004_emaillog_user_smtpconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpconfig',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='smtpconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='default_from',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='port',
            field=models.IntegerField(default=587),
        ),
    ]
